### ISSUE TITLE
Script failure - Cannot find file specified

### ISSUE THREAD

**Issue by DefinetlyNotAI** [thewh1teagle/chrome-privless-encryption#1]
I would like to fix this if you may - via a pr

Here is the output:
```
PS C:\Users\Hp\Desktop> git clone https://github.com/thewh1teagle/chrome-privless-encryption
Cloning into 'chrome-privless-encryption'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 10 (delta 4), reused 7 (delta 1), pack-reused 0 (from 0)
Receiving objects: 100% (10/10), done.
Resolving deltas: 100% (4/4), done.
PS C:\Users\Hp\Desktop> cd .\chrome-privless-encryption\
PS C:\Users\Hp\Desktop\chrome-privless-encryption> python main.py
Traceback (most recent call last):
  File "C:\Users\Hp\Desktop\chrome-privless-encryption\main.py", line 69, in <module>
    start_browser(config['bin'], config['user_data'])
  File "C:\Users\Hp\Desktop\chrome-privless-encryption\main.py", line 55, in start_browser
    subprocess.Popen([bin_path, '--restore-last-session', f'--remote-debugging-port={DEBUG_PORT}', '--remote-allow-origins=*', '--headless', f'--user-data-dir={user_data_path}'], stdout=subprocess.DEVNULL)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by ztuannguyen** [comment]
Thank you so much. I passed

**Comment by DefinetlyNotAI** [comment]
> Thank you so much. I passed

What did you mean by that?

**Comment by DefinetlyNotAI** [comment]
#2 fixes this
